openapi: 3.2.0
info:
  title: C8 Public Credential API
  description: Documentation for C8 Public API
  version: 1.0.0
  contact: {}
servers: []
tags:
- name: Credential
paths:
  /public/v1/credentials:
    get:
      operationId: CredentialController_getCredentials
      summary: GET a list of credentials
      parameters:
      - name: searchTerms
        required: false
        in: query
        description: Filter based on credential name
        schema:
          type: string
      - name: providerType
        required: false
        in: query
        description: Filter based on credential provider type
        schema:
          type: string
      - name: providerName
        required: false
        in: query
        description: Filter based on credential provider name
        schema:
          type: string
      - name: pageNumber
        required: false
        in: query
        description: Page number to return
        schema:
          default: 0
          type: number
      - name: pageSize
        required: false
        in: query
        description: Number of items to return per page
        schema:
          default: 20
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialPageDto'
      tags:
      - Credential
    post:
      operationId: CredentialController_createCredential
      summary: POST a new credential
      parameters: []
      requestBody:
        required: true
        description: Credential object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCredentialDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialDto'
        '400':
          description: Returned when request body is not valid
      tags:
      - Credential
  /public/v1/credentials/{id}:
    put:
      operationId: CredentialController_updateCredential
      summary: PUT a credential
      parameters:
      - name: id
        required: true
        in: path
        description: Id of credential to update
        schema:
          type: string
      requestBody:
        required: true
        description: Credential object to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCredentialDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialDto'
        '400':
          description: Returned when request body is not valid
      tags:
      - Credential
    delete:
      operationId: CredentialController_deleteCredential
      summary: DELETE a credential
      parameters:
      - name: id
        required: true
        in: path
        description: Id of credential to delete
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Credential
components:
  schemas:
    CredentialAspectDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the configuration
        value:
          type: object
          description: Value of the configuration
      required:
      - name
      - value
    CredentialPageDto:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CredentialDto'
        totalFound:
          type: number
          description: Total credentials found
        pageNumber:
          type: number
          description: Requested page, note that it starts with 0
        pageSize:
          type: number
          description: Maximum credentials in one paginated response
      required:
      - items
      - totalFound
      - pageNumber
      - pageSize
    CreateCredentialDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the credential
        providerName:
          type: string
          description: Name of the provider
          enum:
          - AWS
          - GCP
          - GitHub
          - GitLab
          - Azure DevOps
          - AZURE
          - Bitbucket
          - CircleCI
          - CustomPlugin
          - Datadog
          - EmbeddedView
          - HttpClient
          - Jenkins
          - 'Jira '
          - NewRelic
          - OpsGenie
          - PagerDuty
          - Scorecards
          - SonarCloud
          - Splunk
        providerType:
          type: string
          description: Type of the provider
          enum:
          - CLOUD
          - REPOS
          - CICD
          - OTHER
          - ISSUE_TRACKING
          - OMS
          - CODE_INSPECTION
        configuration:
          description: Configuration of the credential
          type: array
          items:
            $ref: '#/components/schemas/CredentialAspectDto'
        status:
          type: string
          description: Status of the credential
          default: true
          enum:
          - ACTIVE
          - DISABLED
          - BROKEN
      required:
      - name
      - providerName
      - providerType
      - configuration
    CredentialDto:
      type: object
      properties:
        id:
          type: string
          description: Credential id
        name:
          type: string
          description: Credential name
        providerName:
          type: string
          description: Credential provider name
          enum:
          - AWS
          - GCP
          - GitHub
          - GitLab
          - Azure DevOps
          - AZURE
          - Bitbucket
          - CircleCI
          - CustomPlugin
          - Datadog
          - EmbeddedView
          - HttpClient
          - Jenkins
          - 'Jira '
          - NewRelic
          - OpsGenie
          - PagerDuty
          - Scorecards
          - SonarCloud
          - Splunk
        providerType:
          type: string
          description: Credential provider type
          enum:
          - CLOUD
          - REPOS
          - CICD
          - OTHER
          - ISSUE_TRACKING
          - OMS
          - CODE_INSPECTION
        orgId:
          type: string
          description: Credential organization id
        configuration:
          description: Credential configuration
          type: array
          items:
            type: array
        status:
          type: string
          description: Credential status
          enum:
          - ACTIVE
          - DISABLED
          - BROKEN
        createdBy:
          type: string
          description: Credential created by
        lastChangedBy:
          type: string
          description: Credential last changed by
        createDateTime:
          format: date-time
          type: string
          description: Credential created at
        lastChangedDateTime:
          format: date-time
          type: string
          description: Credential updated at
        createSchedule:
          type: boolean
          description: Credential updated at
      required:
      - id
      - name
      - providerName
      - providerType
      - orgId
      - configuration
      - status
    UpdateCredentialDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the credential
        configuration:
          description: Configuration of the credential
          type: array
          items:
            type: string
        status:
          type: string
          description: Status of the credential
          enum:
          - ACTIVE
          - DISABLED
          - BROKEN
  securitySchemes:
    api-key:
      type: apiKey
      in: header
      name: Api-Key
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
x-readme:
  explorer-enabled: true
  proxy-enabled: true
